apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-budget-data
  namespace: actual-budget
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
  labels:
    app.kubernetes.io/name: actual-budget
    app.kubernetes.io/part-of: everlab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 20Gi
