apiVersion: v1
kind: Service

metadata:
  name: faster-whisper
  namespace: ai

spec:

  selector:
    app: faster-whisper

  ports:
    - name: wyoming
      port: 10300
      targetPort: 10300

  type: ClusterIP
