apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radicale-auth
  namespace: radicale
  labels:
    app.kubernetes.io/name: radicale
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: everlab-secrets

  target:
    name: radicale-auth
    creationPolicy: Owner
    template:
      type: Opaque

  data:
    - secretKey: users
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: radicale/application
        metadataPolicy: None
        property: users-file
