apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radicale-data
  namespace: radicale
  labels:
    app.kubernetes.io/name: radicale
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: nfs

  resources:
    requests:
      storage: 5Gi
