apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-postgres-user
  namespace: immich
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: everlab-secrets

  target:
    name: immich-postgres-user
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth

  data:
    - secretKey: username
      remoteRef:
        key: immich/postgres
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

    - secretKey: password
      remoteRef:
        key: immich/postgres
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
