apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xcel-itron2mqtt
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"

spec:
  project: default

  source:
    repoURL: https://github.com/sudo-su-556x45/everlab_GitOps_Public.git
    targetRevision: main
    path: kubernetes/applications/bridges/xcel-itron2mqtt

  destination:
    server: https://kubernetes.default.svc
    namespace: xcel-itron2mqtt

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=false
