apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-gpu-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  project: default

  sources:
    - repoURL: https://helm.ngc.nvidia.com/nvidia
      chart: gpu-operator
      targetRevision: "v26.3.3"

      helm:
        releaseName: gpu-operator

        valuesObject:
          operator:
            defaultRuntime: containerd

          cdi:
            enabled: false

          driver:
            enabled: false

          toolkit:
            enabled: true
            env:
              - name: CONTAINERD_SET_AS_DEFAULT
                value: "true"
              - name: NVIDIA_CONTAINER_RUNTIME_MODE
                value: legacy

          devicePlugin:
            enabled: true
            config:
              name: time-slicing-config

          gfd:
            enabled: true

          dcgmExporter:
            enabled: true

          mig:
            strategy: none

    - repoURL: https://github.com/sudo-su-556x45/everlab_GitOps_Public.git
      targetRevision: main
      path: kubernetes/infrastructure/nvidia-gpu-operator

  destination:
    server: https://kubernetes.default.svc
    namespace: gpu-operator

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true

  revisionHistoryLimit: 10
