apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-csi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"

spec:
  project: default

  sources:
    - repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
      chart: csi-driver-nfs
      targetRevision: "4.11.0"

      helm:
        releaseName: csi-driver-nfs

    - repoURL: https://github.com/sudo-su-556x45/everlab_GitOps_Public.git
      targetRevision: main
      path: kubernetes/infrastructure/nfs-csi

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true

  revisionHistoryLimit: 10
