apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-mongodb
  namespace: unifi
  annotations:
    argocd.argoproj.io/sync-wave: "-5"

spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: everlab-secrets

  target:
    name: unifi-mongodb
    creationPolicy: Owner

  data:
    - secretKey: username
      remoteRef:
        key: unifi/mongodb
        property: username

    - secretKey: password
      remoteRef:
        key: unifi/mongodb
        property: password

    - secretKey: rootUsername
      remoteRef:
        key: unifi/mongodb
        property: rootUsername

    - secretKey: rootPassword
      remoteRef:
        key: unifi/mongodb
        property: rootPassword
