apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trek-secret
  namespace: trek
  labels:
    app.kubernetes.io/name: trek
    app.kubernetes.io/part-of: everlab
  annotations:
    argocd.argoproj.io/sync-wave: "-2"

spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: everlab-secrets

  target:
    name: trek-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        ENCRYPTION_KEY: "{{ .encryptionKey }}"
        ADMIN_EMAIL: "{{ .adminEmail }}"
        ADMIN_PASSWORD: "{{ .adminPassword }}"
        UNSPLASH_ACCESS_KEY: "{{ .unsplashAccessKey }}"

  data:
    - secretKey: encryptionKey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: trek/application
        metadataPolicy: None
        property: encryption-key

    - secretKey: adminEmail
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: trek/application
        metadataPolicy: None
        property: admin-email

    - secretKey: adminPassword
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: trek/application
        metadataPolicy: None
        property: admin-password

    - secretKey: unsplashAccessKey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: trek/application
        metadataPolicy: None
        property: unsplash-access-key
