apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nocodb-postgres-user
  namespace: nocodb
  labels:
    app.kubernetes.io/name: nocodb
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: everlab-secrets

  target:
    name: nocodb-postgres-user
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"

  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: nocodb/postgres
        metadataPolicy: None
        property: username

    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: nocodb/postgres
        metadataPolicy: None
        property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nocodb-valkey
  namespace: nocodb
  labels:
    app.kubernetes.io/name: nocodb
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: everlab-secrets

  target:
    name: nocodb-valkey
    creationPolicy: Owner

  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: nocodb/valkey
        metadataPolicy: None
        property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nocodb-secrets
  namespace: nocodb
  labels:
    app.kubernetes.io/name: nocodb
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: everlab-secrets

  target:
    name: nocodb-secrets
    creationPolicy: Owner

  data:
    - secretKey: DATABASE_URL
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: nocodb/application
        metadataPolicy: None
        property: database-url

    - secretKey: NC_REDIS_URL
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: nocodb/application
        metadataPolicy: None
        property: redis-url

    - secretKey: NC_AUTH_JWT_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: nocodb/application
        metadataPolicy: None
        property: jwt-secret

    - secretKey: NC_CONNECTION_ENCRYPT_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: nocodb/application
        metadataPolicy: None
        property: connection-encrypt-key
