---
all:
  children:
    pve0_vms:
      vars:
        system_type: vm
      children:
        pve0_masters:
        pve0_workers:

    pve1_vms:
      vars:
        system_type: vm
      children:
        pve1_workers:

    pve0_masters:
      hosts:
        prod-k8m-01:
          ansible_host: 192.168.10.150
          server_hostname: prod-k8m-01.local.everlab.dev
          k8s_hostname: prod-k8m-01.k8s.everlab.dev
          k8s_cluster_ip: 192.168.11.150
          vm_vcpus: 4
          vm_memory_gib: 8
          k8s_node_roles:
            - control-plane

    pve0_workers:
      hosts:
        prod-k8w-01:
          ansible_host: 192.168.10.151
          server_hostname: prod-k8w-01.local.everlab.dev
          k8s_hostname: prod-k8w-01.k8s.everlab.dev
          k8s_cluster_ip: 192.168.11.151
          vm_vcpus: 12
          vm_memory_gib: 24
          attached_hardware:
            - NVIDIA Quadro P1000
          k8s_node_roles:
            - worker
            - gpu
        prod-k8w-02:
          ansible_host: 192.168.10.152
          server_hostname: prod-k8w-02.local.everlab.dev
          k8s_hostname: prod-k8w-02.k8s.everlab.dev
          k8s_cluster_ip: 192.168.11.152
          vm_vcpus: 12
          vm_memory_gib: 24
          k8s_node_roles:
            - worker
        prod-k8w-03:
          ansible_host: 192.168.10.153
          server_hostname: prod-k8w-03.local.everlab.dev
          k8s_hostname: prod-k8w-03.k8s.everlab.dev
          k8s_cluster_ip: 192.168.11.153
          vm_vcpus: 12
          vm_memory_gib: 24
          k8s_node_roles:
            - worker

    pve1_workers:
      hosts:
        prod-k8w-04:
          ansible_host: 192.168.10.161
          server_hostname: prod-k8w-04.local.everlab.dev
          k8s_hostname: prod-k8w-04.k8s.everlab.dev
          k8s_cluster_ip: 192.168.11.161
          vm_vcpus: 16
          vm_memory_gib: 32
        prod-k8w-05:
          ansible_host: 192.168.10.162
          server_hostname: prod-k8w-05.local.everlab.dev
          k8s_hostname: prod-k8w-05.k8s.everlab.dev
          k8s_cluster_ip: 192.168.11.162
          vm_vcpus: 16
          vm_memory_gib: 32
        prod-k8w-06:
          ansible_host: 192.168.10.163
          server_hostname: prod-k8w-06.local.everlab.dev
          k8s_hostname: prod-k8w-06.k8s.everlab.dev
          k8s_cluster_ip: 192.168.11.163
          vm_vcpus: 16
          vm_memory_gib: 32

    k8s:
      children:
        k8s_masters:
        k8s_workers:

    k8s_masters:
      children:
        pve0_masters:

    k8s_workers:
      children:
        pve0_workers:
        pve1_workers:

    debian_vms:
      children:
        k8s:
