apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-postgres
  namespace: forgejo
  labels:
    app.kubernetes.io/name: forgejo-postgres
    app.kubernetes.io/part-of: forgejo
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  instances: 1

  imageName: ghcr.io/cloudnative-pg/postgresql:17

  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
      secret:
        name: forgejo-postgres-user

  storage:
    storageClass: nfs
    size: 20Gi

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 2Gi

  affinity:
    enablePodAntiAffinity: false

  monitoring:
    enablePodMonitor: true
