apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: code-server
  namespace: code-server
  labels:
    app.kubernetes.io/name: code-server
    app.kubernetes.io/part-of: everlab

spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: everlab-secrets

  target:
    name: code-server
    creationPolicy: Owner

  data:
    - secretKey: password
      remoteRef:
        key: code-server
        property: password
