apiVersion: v1
kind: PersistentVolume
metadata:
  name: code-server-projects
  labels:
    app.kubernetes.io/name: code-server
    app.kubernetes.io/part-of: everlab
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false

spec:
  capacity:
    storage: 500Gi

  accessModes:
    - ReadWriteMany

  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""

  mountOptions:
    - nfsvers=4.1
    - hard
    - timeo=600
    - retrans=2
    - sec=sys

  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: code-server-projects
    volumeAttributes:
      server: 192.168.21.120
      share: /projects
