apiVersion: v1
kind: ConfigMap
metadata:
  name: solaredge2mqtt-config
  namespace: solaredge2mqtt

data:
  configuration.yml: |
    interval: 5
    logging_level: INFO

    modbus:
      host: 192.168.30.11
      port: 1502
      timeout: 2
      unit: 1

      meter:
        - false
        - false
        - false

      battery:
        - false
        - false

      check_grid_status: false

      startup_retry_delay: 30
      startup_retry_max_delay: 300

    mqtt:
      client_id: solaredge2mqtt
      broker: mosquitto.mosquitto.svc.cluster.local
      port: 1883
      username: !secret mqtt_username
      password: !secret mqtt_password
      topic_prefix: solaredge
      use_tls: false

    homeassistant:
      enable: true
      topic_prefix: homeassistant
      retain: true
