apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true

spec:
  project: default

  sources:
    - repoURL: https://kyverno.github.io/kyverno
      chart: kyverno
      targetRevision: "3.8.2"

      helm:
        releaseName: kyverno
        valueFiles:
          - $values/kubernetes/platform/kyverno/values.yaml

    - repoURL: https://github.com/sudo-su-556x45/everlab_GitOps_Public.git
      targetRevision: main
      path: kubernetes/platform/kyverno
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
