apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vikunja-postgres-user
  namespace: vikunja
  labels:
    app.kubernetes.io/name: vikunja
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: everlab-secrets

  target:
    name: vikunja-postgres-user
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"

  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: vikunja/postgres
        metadataPolicy: None
        property: username

    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: vikunja/postgres
        metadataPolicy: None
        property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vikunja-application
  namespace: vikunja
  labels:
    app.kubernetes.io/name: vikunja
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: everlab-secrets

  target:
    name: vikunja-application
    creationPolicy: Owner
    template:
      type: Opaque

  data:
    - secretKey: jwt-secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: vikunja/application
        metadataPolicy: None
        property: jwt-secret
