apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-files
  namespace: vikunja
  labels:
    app.kubernetes.io/name: vikunja
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: nfs

  resources:
    requests:
      storage: 20Gi
