---
k8s_api_port: 6443

kube_vip_version: "v0.9.2"
kube_vip_manifest_path: "/etc/kubernetes/manifests/kube-vip.yaml"

kube_vip_leader_election: true
kube_vip_lease_name: "plndr-cp-lock"
kube_vip_lease_duration: 5
kube_vip_renew_deadline: 3
kube_vip_retry_period: 1
