apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: influxdb-init
  namespace: influxdb
  labels:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/part-of: everlab

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: everlab-secrets
    kind: ClusterSecretStore

  target:
    name: influxdb-init
    creationPolicy: Owner

  data:
    - secretKey: DOCKER_INFLUXDB_INIT_USERNAME
      remoteRef:
        key: influxdb
        property: username

    - secretKey: DOCKER_INFLUXDB_INIT_PASSWORD
      remoteRef:
        key: influxdb
        property: password

    - secretKey: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      remoteRef:
        key: influxdb
        property: token

    - secretKey: DOCKER_INFLUXDB_INIT_ORG
      remoteRef:
        key: influxdb
        property: org

    - secretKey: DOCKER_INFLUXDB_INIT_BUCKET
      remoteRef:
        key: influxdb
        property: bucket

    - secretKey: DOCKER_INFLUXDB_INIT_RETENTION
      remoteRef:
        key: influxdb
        property: retention
