apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: influxdb
  namespace: influxdb
  labels:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/part-of: everlab
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: influxdb

  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
