apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-postgres-user
  namespace: forgejo
  labels:
    app.kubernetes.io/name: forgejo
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: everlab-secrets

  target:
    name: forgejo-postgres-user
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"

  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: forgejo/postgres
        metadataPolicy: None
        property: username

    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: forgejo/postgres
        metadataPolicy: None
        property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-application
  namespace: forgejo
  labels:
    app.kubernetes.io/name: forgejo
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: everlab-secrets

  target:
    name: forgejo-application
    creationPolicy: Owner
    template:
      type: Opaque

  data:
    - secretKey: secret-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: forgejo/application
        metadataPolicy: None
        property: secret-key

    - secretKey: internal-token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: forgejo/application
        metadataPolicy: None
        property: internal-token

    - secretKey: lfs-jwt-secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: forgejo/application
        metadataPolicy: None
        property: lfs-jwt-secret
