apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: forgejo
  namespace: forgejo
  labels:
    app.kubernetes.io/name: forgejo
    app.kubernetes.io/part-of: everlab
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: forgejo

  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
