apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"

spec:
  project: default

  sources:
    - repoURL: https://kubernetes-sigs.github.io/descheduler
      chart: descheduler
      targetRevision: "0.36.0"

      helm:
        releaseName: descheduler
        valueFiles:
          - $values/kubernetes/platform/descheduler/values.yaml

    - repoURL: https://github.com/sudo-su-556x45/everlab_GitOps_Public.git
      targetRevision: main
      path: kubernetes/platform/descheduler
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
