apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - pvc.yaml
  - transcode-pvc.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml

labels:
  - pairs:
      app.kubernetes.io/name: ersatztv
      app.kubernetes.io/part-of: media-stack
      app.kubernetes.io/component: media-server
    includeSelectors: true
