apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ersatztv-config
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: nfs

  resources:
    requests:
      storage: 20Gi
