apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ring-mqtt-data
  namespace: ring-mqtt
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: nfs

  resources:
    requests:
      storage: 1Gi
