apiVersion: v1
kind: Service
metadata:
  name: ring-mqtt
  namespace: ring-mqtt

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: ring-mqtt

  ports:
    - name: web
      port: 55123
      targetPort: 55123
      protocol: TCP
