apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default

  sources:
    - repoURL: https://helm.cilium.io
      chart: cilium
      targetRevision: "1.19.6"
      helm:
        releaseName: cilium
        valueFiles:
          - $values/kubernetes/infrastructure/cilium/values.yaml

    - repoURL: https://github.com/sudo-su-556x45/everlab_GitOps_Public.git
      targetRevision: main
      path: kubernetes/infrastructure/cilium
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - PruneLast=true
