apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy-config
  namespace: ntfy
  labels:
    app.kubernetes.io/name: ntfy
    app.kubernetes.io/part-of: everlab
data:
  server.yml: |
    base-url: https://ntfy.prod.everlab.dev
    listen-http: :8080
    cache-file: /var/cache/ntfy/cache.db
    attachment-cache-dir: /var/cache/ntfy/attachments
    metrics-listen-http: ":9090"
    behind-proxy: true
    enable-login: true
    auth-default-access: read-write
