apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wiki-js-postgres-user
  namespace: wiki-js
  labels:
    app.kubernetes.io/name: wiki-js
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: everlab-secrets

  target:
    name: wiki-js-postgres-user
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"

  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: wiki-js/postgres
        metadataPolicy: None
        property: username

    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: wiki-js/postgres
        metadataPolicy: None
        property: password
