apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"

spec:
  project: default

  sources:
    - repoURL: https://stakater.github.io/stakater-charts
      chart: reloader
      targetRevision: "2.2.14"

      helm:
        releaseName: reloader

        valuesObject:
          reloader:
            watchGlobally: true

            deployment:
              replicas: 1

            readOnlyRootFileSystem: true

            resources:
              requests:
                cpu: 20m
                memory: 64Mi
              limits:
                memory: 256Mi

            podMonitor:
              enabled: true
              interval: 30s
    - repoURL: https://github.com/sudo-su-556x45/everlab_GitOps_Public.git
      targetRevision: main
      path: kubernetes/platform/reloader

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true

  revisionHistoryLimit: 10
