apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: matrix-synapse
  namespace: matrix
  labels:
    app.kubernetes.io/name: matrix
    app.kubernetes.io/part-of: everlab
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: matrix

  endpoints:
    - port: metrics
      path: /_synapse/metrics
      interval: 30s
      scrapeTimeout: 10s
