apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: telegraf-secrets
  namespace: telegraf

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: everlab-secrets
    kind: ClusterSecretStore

  target:
    name: telegraf-secrets
    creationPolicy: Owner

  data:
    - secretKey: MQTT_USERNAME
      remoteRef:
        key: mosquitto/auth
        property: username

    - secretKey: MQTT_PASSWORD
      remoteRef:
        key: mosquitto/auth
        property: password

    - secretKey: INFLUX_TOKEN
      remoteRef:
        key: influxdb
        property: token
