apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/part-of: everlab
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/sudo-su-556x45/everlab_GitOps_Public.git
    targetRevision: main
    path: kubernetes/applications/n8n

  destination:
    server: https://kubernetes.default.svc
    namespace: n8n

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
