apiVersion: v1
kind: ConfigMap
metadata:
  name: everlab-ca
  namespace: unifi
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIICizCCAhKgAwIBAgIQRj0msVD01WEtp3TvGL8oMDAKBggqhkjOPQQDAzA1MRAw
    DgYDVQQKEwdFdmVyTGFiMSEwHwYDVQQDExhFdmVyTGFiIEludGVybmFsIFJvb3Qg
    Q0EwHhcNMjYwODEyMDIyOTQ5WhcNMjYxMTEwMDIyOTQ5WjAAMIIBIjANBgkqhkiG
    9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsDxQ6nMeXsJ79Y/aabMQxb/EsaM9Uc0X/66Q
    q+JoVtx8aIAcesT/KpEahDEtJdMBbfKEerRZ+8bIE17ShoHb9cH5bm+L8FUWAHGO
    GQNwKogx3ECq4sB2OqGbHCqqyH7pd6OIGFv1aoUb31cVbY3YE3uZDpzgnv5tI0y6
    rDULOl+V0YGHKWLKyHOSFg2IHDgY9FCVDrGTkuGBj7q8pRF1jrSBtStRpaS+ZkV1
    qO6B3T1l82VG2IAEKE47kc4RmorLDP/EWNmfz+mAvlE8diD1pUJWG5HsTar9PlGh
    9WOuzBcicGGs0Vrj9aW4GMt+Qk1ILOANn6AjdqPiOrop1QUKAwIDAQABo24wbDAO
    BgNVHQ8BAf8EBAMCBaAwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBTJYIS80JSL
    EA7xClWF4NLUxmE6SjArBgNVHREBAf8EITAfgh11bmlmaS51bmlmaS5zdmMuY2x1
    c3Rlci5sb2NhbDAKBggqhkjOPQQDAwNnADBkAjAKeVEHqHDotW6zmot5AmrDDLbM
    j28jLAWtszTluSGzAexHXhiOSJfp5N/dHLjEpKICMC2Mqt24/ElfnQ3PAPACkzLt
    GOTig9mC8xlqBPujQHAh6a76gimCud2osvzpbHxnPw==
    -----END CERTIFICATE-----
