apiVersion: v1
kind: Service
metadata:
  name: unifi-mongodb
  namespace: unifi

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: unifi-mongodb

  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
      protocol: TCP
