apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - faster-whisper/application.yaml
  - piper/application.yaml
  - open-webui/application.yaml
  - ollama/application.yaml
