apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
  namespace: frigate
  labels:
    app.kubernetes.io/name: frigate
    app.kubernetes.io/part-of: everlab
data:
  config.yml: |
    mqtt:
      enabled: false

    detectors:
      cpu:
        type: cpu

    cameras: {}

    record:
      enabled: false

    version: 0.17-0
