apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config
  namespace: frigate
  labels:
    app.kubernetes.io/name: frigate
    app.kubernetes.io/part-of: everlab
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: nfs

  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media
  namespace: frigate
  labels:
    app.kubernetes.io/name: frigate
    app.kubernetes.io/part-of: everlab
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: nfs

  resources:
    requests:
      storage: 500Gi
