apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: everlab-ipa
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  acme:
    server: https://prod-ipa-01.local.everlab.dev/acme/directory

    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVuVENDQXdXZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREE4TVJvd0dBWURWUVFLREJGTVQwTkIKVEM1RlZrVlNURUZDTGtSRlZqRWVNQndHQTFVRUF3d1ZRMlZ5ZEdsbWFXTmhkR1VnUVhWMGFHOXlhWFI1TUI0WApEVEl6TURnek1EQXhNemd6TjFvWERUUXpNRGd6TURBeE16Z3pOMW93UERFYU1CZ0dBMVVFQ2d3UlRFOURRVXd1ClJWWkZVa3hCUWk1RVJWWXhIakFjQmdOVkJBTU1GVU5sY25ScFptbGpZWFJsSUVGMWRHaHZjbWwwZVRDQ0FhSXcKRFFZSktvWklodmNOQVFFQkJRQURnZ0dQQURDQ0FZb0NnZ0dCQU8veTdJdzlUc3psSVhwR2d2alR1bVBjTDlLcgpFOFpKM3gzVk1zL1JsL1hGOCt3N3VrSGMzY1doeldhSElzazZGYjZQNU9XZ3BIT1BWWHl3eXNhL1BJK1djdWRFCmNJTlgyQUp0czF4Y0FpWVMvdXRheWJUcFdvRjErNE9lMWFhVUtEZjhaT2x6WTk2V09xUTdrai9YQWdGZlRBeHoKTVo5V3lKcXg0d2JZSTdOWjVvRWpyRlBsZkxyRS92L2hsMHpCbndZZHJxNlJ1QnduK25YOVpzV1VGVFRXTnhpagpNSVdSS3ZET3NOK1U0dEFscGNiKzEvUEliTDIxZXdjVmJDc3VBUS9jM3J2dFFRSHM5aEdNRGkwOGxuMzFSOElPClFMZ0E4UVE4QXZOeVhvaEJzZFc1MG03WUhnS3BQOEdxc0VHd0lsVStTNDFrMXpQZS9PeUt5WkwzR2d5ZmVpN1MKSzVhdU1haEp0SEtFVnFxV3lSVHd2TnE3QkFYWUFKNHpEODhXVnVrR296cjNSUG5Wa28wdG5na2o2ZHI5SER0TgpVa3lxUG5Ob3hxREJHM1lHZUl2ekk4WEkxWXRtTFgxSGpud3RtUnVkRi9NQmZSZzdnbmMxNC9HNklNMkVweWlvCmxIUkwvT1drZFhGSllvK0M5WnZYMStadFdCSFNBdHQ0aVhoeUdRSURBUUFCbzRHcE1JR21NQjhHQTFVZEl3UVkKTUJhQUZGNjgyUEFkNkZyZG50Z3BpbmovbTFoc1h3L2hNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUApBUUgvQkFRREFnSEdNQjBHQTFVZERnUVdCQlJldk5qd0hlaGEzWjdZS1lwNC81dFliRjhQNFRCREJnZ3JCZ0VGCkJRY0JBUVEzTURVd013WUlLd1lCQlFVSE1BR0dKMmgwZEhBNkx5OXBjR0V0WTJFdWJHOWpZV3d1WlhabGNteGgKWWk1a1pYWXZZMkV2YjJOemNEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FZRUFKV0xBQUtFMVZYemNxMlFHQjQyWgp4a0xwUVJQaGczR3c0bStFVWhWYnQ0b0l0MVBHQ3BudVlFMm1CLzZNald3QU14ckZHY09KZ0JQVWZZUkFoS041Ck1SMkRzbS9QTmd4SDI5Mlp1ZVpLdzZRVXFZa3ZlS1dBS2k3Y1pxRVRTbmlkUG9uaWxhSlBsNDRZTlQvM2xqMGUKV1Z5R0VUcHl2UGxVa3IwRHZVbldnempvOG93dHlyT1V6ZDdxQThTNldZZE5qQW0vOUpMc2ZNRHp3dUdobjJrWAp3R3FTd05yTU9WZzRoWTVvVnhYSHdLblRSaDFZU2JNMlkzamFLbEdTc1VIWTJBRFBmdHhLNnpiVC9wenBtZW5vClFCVkRTazc1cFBWd3VJbmEwNEZ3SGE1NkI1QWFpVkNtWjFiVHJSeTczMkFaNFJtTVlyUmIvNVc3RUNQVmtLZU8KZkdUVTQyNUVZVkJUNS9Cb2ltSXFLRm45MGFnMVBjTVNrMjY4bk1ibll3cWRXbGdKMGNaY0U5d3QrYVJITEV3RgpMbE92c2JvQjhQTzZ4QVZDL0lPZFFQVXpFM1RUcm1scWFVaXFEQlROdzgyNjNxbWN2R1lzdC8xRTFPVTZtQUtjCkd1WUtFbnl3MHhFaFBPMUV5R2NNWm9jN2ZOUnlKTXFVOWY5eXdMNmtMMDJPCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"

    privateKeySecretRef:
      name: everlab-ipa-acme-account

    solvers:
      - dns01:
          rfc2136:
            nameserver: 192.168.10.103:53
            tsigKeyName: external-dns.prod.everlab.dev.
            tsigAlgorithm: HMACSHA256
            tsigSecretSecretRef:
              name: external-dns-tsig
              key: tsig-secret
