apiVersion: v1
kind: ConfigMap
metadata:
  name: everlab-ipa-ca
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/part-of: everlab

data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEnTCCAwWgAwIBAgIBATANBgkqhkiG9w0BAQsFADA8MRowGAYDVQQKDBFMT0NB
    TC5FVkVSTEFCLkRFVjEeMBwGA1UEAwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4X
    DTIzMDgzMDAxMzgzN1oXDTQzMDgzMDAxMzgzN1owPDEaMBgGA1UECgwRTE9DQUwu
    RVZFUkxBQi5ERVYxHjAcBgNVBAMMFUNlcnRpZmljYXRlIEF1dGhvcml0eTCCAaIw
    DQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAO/y7Iw9TszlIXpGgvjTumPcL9Kr
    E8ZJ3x3VMs/Rl/XF8+w7ukHc3cWhzWaHIsk6Fb6P5OWgpHOPVXywysa/PI+WcudE
    cINX2AJts1xcAiYS/utaybTpWoF1+4Oe1aaUKDf8ZOlzY96WOqQ7kj/XAgFfTAxz
    MZ9WyJqx4wbYI7NZ5oEjrFPlfLrE/v/hl0zBnwYdrq6RuBwn+nX9ZsWUFTTWNxij
    MIWRKvDOsN+U4tAlpcb+1/PIbL21ewcVbCsuAQ/c3rvtQQHs9hGMDi08ln31R8IO
    QLgA8QQ8AvNyXohBsdW50m7YHgKpP8GqsEGwIlU+S41k1zPe/OyKyZL3Ggyfei7S
    K5auMahJtHKEVqqWyRTwvNq7BAXYAJ4zD88WVukGozr3RPnVko0tngkj6dr9HDtN
    UkyqPnNoxqDBG3YGeIvzI8XI1YtmLX1HjnwtmRudF/MBfRg7gnc14/G6IM2Epyio
    lHRL/OWkdXFJYo+C9ZvX1+ZtWBHSAtt4iXhyGQIDAQABo4GpMIGmMB8GA1UdIwQY
    MBaAFF682PAd6Frdntgpinj/m1hsXw/hMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0P
    AQH/BAQDAgHGMB0GA1UdDgQWBBRevNjwHeha3Z7YKYp4/5tYbF8P4TBDBggrBgEF
    BQcBAQQ3MDUwMwYIKwYBBQUHMAGGJ2h0dHA6Ly9pcGEtY2EubG9jYWwuZXZlcmxh
    Yi5kZXYvY2Evb2NzcDANBgkqhkiG9w0BAQsFAAOCAYEAJWLAAKE1VXzcq2QGB42Z
    xkLpQRPhg3Gw4m+EUhVbt4oIt1PGCpnuYE2mB/6MjWwAMxrFGcOJgBPUfYRAhKN5
    MR2Dsm/PNgxH292ZueZKw6QUqYkveKWAKi7cZqETSnidPonilaJPl44YNT/3lj0e
    WVyGETpyvPlUkr0DvUnWgzjo8owtyrOUzd7qA8S6WYdNjAm/9JLsfMDzwuGhn2kX
    wGqSwNrMOVg4hY5oVxXHwKnTRh1YSbM2Y3jaKlGSsUHY2ADPftxK6zbT/pzpmeno
    QBVDSk75pPVwuIna04FwHa56B5AaiVCmZ1bTrRy732AZ4RmMYrRb/5W7ECPVkKeO
    fGTU425EYVBT5/BoimIqKFn90ag1PcMSk268nMbnYwqdWlgJ0cZcE9wt+aRHLEwF
    LlOvsboB8PO6xAVC/IOdQPUzE3TTrmlqaUiqDBTNw8263qmcvGYst/1E1OU6mAKc
    GuYKEnyw0xEhPO1EyGcMZoc7fNRyJMqU9f9ywL6kL02O
    -----END CERTIFICATE-----
