apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: plex
  labels:
    app.kubernetes.io/name: plex
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: plex
  ports:
    - name: http
      port: 32400
      targetPort: http
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: plex-remote
  namespace: plex
  labels:
    app.kubernetes.io/name: plex
    app.kubernetes.io/part-of: everlab
  annotations:
    lbipam.cilium.io/ips: "192.168.12.102"
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false

  selector:
    app.kubernetes.io/name: plex

  ports:
    - name: plex
      protocol: TCP
      port: 32400
      targetPort: 32400
