apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-tsig
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: everlab-secrets
    kind: ClusterSecretStore
  target:
    name: external-dns-tsig
    creationPolicy: Owner
  data:
    - secretKey: tsig-secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: external-dns/tsig
        metadataPolicy: None
        property: tsig-secret
