apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring

spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: everlab-secrets

  target:
    name: grafana-admin
    creationPolicy: Owner
    template:
      type: Opaque

  data:
    - secretKey: admin-user
      remoteRef:
        key: monitoring/grafana
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

    - secretKey: admin-password
      remoteRef:
        key: monitoring/grafana
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
