apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hyperhdr
  namespace: argocd
  labels:
    app.kubernetes.io/name: hyperhdr
    app.kubernetes.io/part-of: media-stack

spec:
  project: default

  source:
    repoURL: https://github.com/sudo-su-556x45/everlab_GitOps_Public.git
    targetRevision: main
    path: kubernetes/applications/media/hyperhdr

  destination:
    server: https://kubernetes.default.svc
    namespace: media

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
