apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-assistant-data
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 10Gi
