apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-tunnel-token
  namespace: cloudflared
  labels:
    app.kubernetes.io/name: cloudflared
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: everlab-secrets

  target:
    name: cloudflared-tunnel-token
    creationPolicy: Owner
    template:
      type: Opaque

  data:
    - secretKey: token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: cloudflared/prod
        metadataPolicy: None
        property: tunnel-token
