apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cloudflared
  namespace: cloudflared
  labels:
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/part-of: everlab
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflared

  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
