apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-postgres-user
  namespace: paperless-ngx
  labels:
    app.kubernetes.io/name: paperless-ngx
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: everlab-secrets

  target:
    name: paperless-postgres-user
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"

  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: paperless/postgres
        metadataPolicy: None
        property: username

    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: paperless/postgres
        metadataPolicy: None
        property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-application
  namespace: paperless-ngx
  labels:
    app.kubernetes.io/name: paperless-ngx
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: everlab-secrets

  target:
    name: paperless-application
    creationPolicy: Owner

  data:
    - secretKey: secret-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: paperless/application
        metadataPolicy: None
        property: secret-key
