apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - settings.yaml
  - storage.yaml
  - ersatztv/application.yaml
  - hyperhdr/application.yaml
  - music-assistant/application.yaml
