apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-data
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  capacity:
    storage: 100Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media-nfs
  mountOptions:
    - nfsvers=4.1
    - hard
    - noatime
  nfs:
    server: 192.168.21.121
    path: /plex
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data
  namespace: media
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media-nfs
  volumeName: media-data
  resources:
    requests:
      storage: 100Ti
