apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config-pvc.yaml
  - httproute.yaml
  - media-pv.yaml
  - media-pvc.yaml
  - transcode-pvc.yaml
  - transcode-storageclass.yaml
