apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media
  namespace: plex
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: plex-media-static
  volumeName: plex-media
  resources:
    requests:
      storage: 50Ti
