apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-transcode
  namespace: plex
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: plex-transcode-local
  resources:
    requests:
      storage: 100Gi
