apiVersion: v1
kind: ConfigMap
metadata:
  name: element-config
  namespace: matrix
  labels:
    app.kubernetes.io/name: element
    app.kubernetes.io/part-of: matrix
data:
  config.json: |
    {
      "brand": "Element",
      "default_server_config": {
        "m.homeserver": {
          "base_url": "https://matrix.prod.everlab.dev",
          "server_name": "matrix.prod.everlab.dev"
        }
      },
      "disable_custom_urls": true,
      "disable_guests": true,
      "disable_login_language_selector": false,
      "show_labs_settings": false
    }
